spring:
  application:
    name: ledgeflow

  datasource:
    url: jdbc:postgresql://localhost:5432/ledgeflow
    username: ledgeflow
    password: ledgeflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
